### ISSUE TITLE
Can't upgrade to OrientDB 2.1.x

### ISSUE THREAD

**Issue by pires** [orientechnologies/spring-data-orientdb#26]
See https://github.com/orientechnologies/orientdb/issues/4414

**Comment by lvca** [comment]
If this is the problem,  could you change the WHERE in WHILE?

**Comment by pires** [comment]
Actually, all the tests fail with a similar but not the same error:

```
findByLastNameLike(org.springframework.data.orient.object.repository.PersonRepositoryTest)  Time elapsed: 0.002 sec  <<< FAILURE!
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered "" at line 1, column 28.
Was expecting one of:

	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:102)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:238)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:219)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:95)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1447)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:686)
	at com.orientechnologies.orient.object.db.ODatabasePojoAbstract.query(ODatabasePojoAbstract.java:242)
	at org.springframework.data.orient.commons.core.AbstractOrientOperations.query(AbstractOrientOperations.java:557)
	at org.springframework.data.orient.commons.core.AbstractOrientOperations.query(AbstractOrientOperations.java:562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy38.query(Unknown Source)
	at org.springframework.data.orient.commons.repository.query.OrientQueryExecution$CollectionExecution.doExecute(OrientQueryExecution.java:74)
	at org.springframework.data.orient.commons.repository.query.OrientQueryExecution.execute(OrientQueryExecution.java:40)
	at org.springframework.data.orient.commons.repository.query.AbstractOrientQuery.doExecute(AbstractOrientQuery.java:58)
	at org.springframework.data.orient.commons.repository.query.AbstractOrientQuery.execute(AbstractOrientQuery.java:47)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:413)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:391)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy43.findByLastNameLike(Unknown Source)
	at org.springframework.data.orient.object.repository.PersonRepositoryTest.findByLastNameLike(PersonRepositoryTest.java:127)
```

Any hints, @lvca?

**Comment by lvca** [comment]
@luigidellaquila do you have any idea on this?

**Comment by luigidellaquila** [comment]
@lvca not actually, I should see the query that is failing...

**Comment by Alan47** [comment]
I'm having the same problem with OrientDB 2.1.0.

The following line causes the issue for me when I generate the graph schema:

    OrientVertexType vertexType = ...; // some vertex type
    OType propertyType = ...; // some OType
    String name = ...; // the name of the property, arbitrary string
    vertexType.createProperty(name, propertyType);  // <--- CRASH


Here's the exact stack trace:

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered "" at line 1, column 37.
Was expecting one of:
    
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:102)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:238)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:219)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:95)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1447)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1942)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1638)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2340)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:799)
	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createProperty(OClassAbstractDelegate.java:165)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$201(OrientElementType.java:35)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$3.call(OrientElementType.java:70)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$3.call(OrientElementType.java:67)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1740)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.createProperty(OrientElementType.java:67)
	at com.tinkerpop.blueprints.impls.orient.OrientVertexType.createProperty(OrientVertexType.java:111)

**Comment by eugene-kamenev** [comment]
@Alan47 I actually did the same, but with OClass, not OrientVertexType, can you check if it works. For me it works fine in 2.1.0

**Comment by Alan47** [comment]
@eugene-kamenev I had a look at the Orient DB Graph API. It appears that all the graph API really does in and on itself is generating SQL statements for the document engine to process. My best guess for this error would be that the SQL syntax was changed in the Orient DB core, but somebody forgot to update the automatic generator for the statements in the graph API.

So, if it works with OClass for you, then very likely, OrientVertexType is the culprit.

**Comment by lvca** [comment]
What's the property name that cause such problem? I bet it has invalid characters like "-".

**Comment by lvca** [comment]
With new parser names like "amount-vat" are invalid, because, like in SQL, you could ask to subtract vat to the amount. We supported backtick (`) to encode names. Example:

    create property `User.name-with-no-surname` STRING

Please could you test 2.1.1 if has the same problem?

**Comment by Alan47** [comment]
Hello,

I just downloaded 2.1.1 and ran my test suite against it. Indeed, as you said, several property names contain a "-" character. With 2.1.1, I get a very precise error message that is a lot clearer than before, thanks a lot for that.
