### ISSUE TITLE
IllegalStateException when trying deleteByXYZ or removeByXYZ

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#55]
While trying to delete vertices using Orient Spring Data, I am received an IllegalStateException.  I tried both deleteByXYZ and removeByXYZ.  Listed below is the stack trace.  Can someone please take a look.  

Thanks,
Ronnie

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:775) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:366) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.orientdb.hello.HelloApplication.main(HelloApplication.java:33) [classes/:na]
Caused by: java.lang.IllegalArgumentException: null
	at org.springframework.data.orient.commons.repository.query.AbstractOrientQuery.getExecution(AbstractOrientQuery.java:119) ~[spring-data-orientdb-commons-0.13-SNAPSHOT.jar:na]
	at org.springframework.data.orient.commons.repository.query.AbstractOrientQuery.execute(AbstractOrientQuery.java:47) ~[spring-data-orientdb-commons-0.13-SNAPSHOT.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:462) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at com.sun.proxy.$Proxy57.removeByAge(Unknown Source) ~[na:na]
	at org.springframework.boot.orientdb.hello.HelloApplication.run(HelloApplication.java:93) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	... 7 common frames omitted

**Comment by RAndrews137** [comment]
Issue above can be reproduced using the Hello example provided.  Modifying the example as follow will trigger the exception:

//repository interface
Long deleteByAge(Integer age);

//Hello Application
Person kaitlin = new Person();
kaitlin.setFirstName("Kaitlin");
kaitlin.setLastName("Walter");
kaitlin.setAge(22);
persons.add(kaitlin);
            
repository.save(persons);

//throws IllegalArgumentException.  Related to: AbstractOrientQuery.getExecution() not matching on any if block.  Falls through and hits throw clause            
Long numDeleted = repository.deleteByAge(22);

**Comment by robfrank** [comment]
thanks, will check

**Comment by RAndrews137** [comment]
I have been looking at the code.  Looks like the Operations interface already has delete capability.  I think a new OrientQueryExecution implementation class for delete would be needed which could call the operations.delete method.  However, the AbstractOrientQuery would still need a way to detect that it is a delete call so that it can use the appropriate implementation.  I hope that made sense  ;)

**Comment by RAndrews137** [comment]
I made a few changes locally to the Orient Spring Data code and have a working prototype for deleteBy.  It would be better if an official implementation was given.  I can share what I did.  Basically, I created a new OrientExecution for deletion.  I used the operations.command method.  I didn't know how to get it to auto-generate the delete syntax, so my current implementation relies on the user annotating the deleteBy method.  That might be less desirable, but it works for now  ;)

**Comment by robfrank** [comment]
Please share it!

**Comment by robfrank** [comment]
I added deletion support, and updated the repository and controller on hello sample

a call to http://localhost:8080/persons/deleteByAge?age=21 will delete the record.

Note that now the sample works with an in-memory embedded db, just for tests.

**Comment by RAndrews137** [comment]
Excellent.  I also just opened an item for countBy when using an annotated query.  Can you please take a look at that one.  I was able to get it working by just updating StringBasedOrientQuery to set isCount to true when the method name startsWith "countBy".
